# Site settings
title: Osiągnij Cele
email: krzysztof.wawer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Osiągni swoje cele życiowe. Zaprojektuj życie pod siebie.
domain: osiagnijcele.pl
url: "https://osiagnijcele.pl" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: wafcio
github_username:  wafcio

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "page:num"

date_locale: pl

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - month
    - categories
  layouts:
    month: archive/month
    category: archive/category
